# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
